import { useState } from "react";
import Hero from "./components/Hero";
import Search from "./components/Search";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";

import "./App.css";

function App() {
  const [count, setCount] = useState(0);

  return (
    <main className="text-white">
      <Hero />
      <Search />
    </main>
  );
}

export default App;

// import { Rubik } from "next/font/google";
// import "./globals.css";

// const rubik = Rubik({
//   variable: "--font-rubik",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
//           integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
//           crossOrigin="anonymous"
//           referrerPolicy="no-referrer"
//         />
//       </head>
//       <body className={`${rubik.variable} antialiased`}>{children}</body>
//     </html>
//   );
// }
